name: Build
on:
  push:

jobs:
  Build:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Get Marvinette
        run: git clone https://github.com/Arthi-chaud/Marvinette.git && cd Marvinette && sudo php MarvinetteInstall.php && cd ..
      - name: Install stack
        run: yes | sudo dnf install stack ghc haskell-platform
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - name: Compile Project
        run: make ; test $(find .stack-work/install -wholename "*/bin/HAL" | wc -l) = "1"
