name: Build
on:
  push:
    branches:
      - master
      - dev
jobs:
  Build:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Get Marvinette
        run: git clone https://github.com/Arthi-chaud/Marvinette.git && cd Marvinette && sudo php MarvinetteInstall.php && cd ..
      - name: Enable Stakc installation
        run: echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
      - uses: mstksg/setup-stack@v1
        name: Install Stack
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Compile Project
        run: make
