name: Build
on:
  push:

jobs:
  Build:
    runs-on: ubuntu-20.04
    container: arthichaud/ci_docker_image
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install stack
        run: yes | curl -sSL https://get.haskellstack.org/ | sh
      - name: Update make
        run: |
          env
          yes | apt-get install make
          yes | apt-get upgrade
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - name: Compile Project
        run: make
        shell: bash
