name: Build
on:
  push:

jobs:
  Build:
    runs-on: ubuntu-20.04
    container: arthichaud/ci_docker_image
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Get Marvinette
        run: git clone https://github.com/Arthi-chaud/Marvinette.git && cd Marvinette && sudo php MarvinetteInstall.php && cd ..
      - name: Install stack
        run: yes | curl -sSL https://get.haskellstack.org/ | sh
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - name: Compile Project
        run: make
