name: Unit tests
on:
  push:
    branches:
      - master
      - dev
jobs:
  ExecUnitTests:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Get Marvinette
        run: git clone https://github.com/Arthi-chaud/Marvinette.git && cd Marvinette && sudo php MarvinetteInstall.php && cd ..
      - uses: actions/setup-haskell@v1.1
        with:
          enable-stack: true
          stack-version: 'latest'
        name: Install Stack
      - name: Run tests
        run: stack test
